# Generated by Django 6.0.4 on 2026-04-19 05:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Painting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('artist_name', models.CharField(max_length=100)),
                ('style', models.CharField(choices=[('fantasy', 'Fantasy Art'), ('digital', 'Digital Art'), ('modern', 'Modern Art'), ('abstract', 'Abstract'), ('portrait', 'Portrait'), ('landscape', 'Landscape')], default='digital', max_length=30)),
                ('description', models.TextField(blank=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('image', models.ImageField(blank=True, null=True, upload_to='paintings/')),
                ('emoji', models.CharField(default='🎨', help_text='Emoji shown when no image uploaded', max_length=10)),
                ('aura_popularity', models.IntegerField(default=80, help_text='Artist popularity score (0-100)')),
                ('aura_uniqueness', models.IntegerField(default=80, help_text='Uniqueness score (0-100)')),
                ('aura_interest', models.IntegerField(default=80, help_text='Buyer interest score (0-100)')),
                ('aura_expert', models.IntegerField(default=80, help_text='Expert review score (0-100)')),
                ('is_featured', models.BooleanField(default=False)),
                ('is_available', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-is_featured', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PaintingRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=15)),
                ('address', models.TextField()),
                ('image', models.ImageField(blank=True, help_text='Upload a reference image or inspiration photo', null=True, upload_to='requests/')),
                ('description', models.TextField(help_text='Describe what you want painted in detail')),
                ('preferred_style', models.CharField(blank=True, choices=[('fantasy', 'Fantasy Art'), ('digital', 'Digital Art'), ('modern', 'Modern Art'), ('abstract', 'Abstract'), ('portrait', 'Portrait'), ('landscape', 'Landscape')], default='digital', max_length=30)),
                ('preferred_size', models.CharField(blank=True, help_text='e.g. A4, A3, 24x36 inches', max_length=50)),
                ('budget', models.CharField(blank=True, help_text='Your approximate budget in INR', max_length=50)),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('accepted', 'Accepted'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('admin_notes', models.TextField(blank=True, help_text='Internal notes for admin')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='painting_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
